#!/usr/bin/env bash -i


# -----------------------------------------------------------------------------
#
# Copyright 2019 Praveen G Shirali <praveengshirali@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# -----------------------------------------------------------------------------


log () { echo -e "$@"; }
err () { >&2 log "ERROR:" "$@"; }


readonly _WORKBENCH_VERSION=0.0.1
readonly _PROG="${0##*/}"


WORKBENCH_GREPPER="${WORKBENCH_GREPPER:-egrep}"


_wb_consume_rcfile () {
    local wbrc="${HOME}/.workbenchrc"
    if [[ -z "${WORKBENCH_RC}" ]] && [[ ! -z "${HOME}" ]] && [[ -f "${wbrc}" ]]
    then
        WORKBENCH_RC="${wbrc}"
    fi
    if [[ ! -z ${WORKBENCH_RC} ]]; then
        if [[ -f "${WORKBENCH_RC}" ]]; then
            source "${WORKBENCH_RC}"
        else
            err "Can't find WORKBENCH_RC: '${WORKBENCH_RC}'"
            exit 1
        fi
    fi
}

_wb_init_workbench_home () {
    [[ -z "${WORKBENCH_HOME}" ]] && WORKBENCH_HOME="${HOME}/.workbench"
    mkdir -p "${WORKBENCH_HOME}"
    if [[ ! -d "${WORKBENCH_HOME}" ]]; then
        err "WORKBENCH_HOME (${WORKBENCH_HOME}) does not exist. Quitting!"
        exit 1
    fi
}


_wb_do_vars () { set | ${WORKBENCH_GREPPER} "^WORKBENCH_\w+=" | sort; }


main () {
    _wb_consume_rcfile
    WORKBENCH_HOME="$(echo ${WORKBENCH_HOME} | sed 's|/*$||g')"
    _wb_init_workbench_home
    if [[ -z "$1" ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
        _wb_show_help
        exit 0
    fi

    case "$1" in
        -V) log "${_WORKBENCH_VERSION}";;
        -E) _wb_do_vars;;
    esac
}


main "$@"
